#服务配置
server:
  port: 9000
  context-path: /aiom
#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      yyx:
        website:
          mapper: debug
#context-listener监听
context:
  listener:
    classes: com.yyx.aio.config.listener.ApplicationEventListener
#数据库配置
spring:
  application:
    name: aiom
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    #datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://192.168.1.191:3306/aiom?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    #username: root
    #password: root
    #driver-class-name: com.mysql.jdbc.Driver
    #filters: stat,wall,log4j
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #tomcat:
    #min-idle: 5
    #max-active: 20
    #initial-size: 5
    #max-wait: 60000
    #time-between-eviction-runs-millis: 60000
    #min-evictable-idle-time-millis: 300000
    #dbcp2:
    #cache-state: false

  servlet:
    multipart:
      enabled: true
      location: D:/spring-boot-aiom-upload/tmp
      file-size-threshold: 5MB
      max-file-size: 20MB

  thymeleaf:
    #mode: HTML5
    mode: LEGACYHTML5  #非严格模式
    encoding: UTF-8
    content-type: text/html
    cache: false

    #mybatis配置
    #mybatis:
    #mapper-locations: classpath:/mybatis/*.xml
    #configuration:
    #map-underscore-to-camel-case: true
    #use-column-label: true
    #type-aliases-package: com.yyx.aio.entity
    #查看运行情况。是否敏感
    #management:
    #security:
    #enabled: false


dbf:
  store:
    location_id: "7023"
    store_id: "01060125"
    store_name: "满记甜品"
    FBPosDataBaseUrl: C:\PointSoft\FBPos\data
    EodDataBaseUrl: C:\PointSoft\Eod\
    url: ""
    urlStr: ""
    desKey: ""
    corporationCode: ""
    publicKeyStr: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCIsGBo7H2RwlwS0p01THCCA8vX6keZ143G+pP1MMtDve9lPPgRt2IAUAmGc/79a9O69C1u5j+ebdK9a5BfjXwQcyEgV2nRlJjr83O0zwoTp6Mc4WuT5ACNGrHUdijxBW9O+pZRmql5nZES8HrkKb0EtsF6PRguqmFsxg1t3eeqSQIDAQAB"
